version: "3.9"

services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - tp3-network

  script:
    build: ./php
    container_name: script
    volumes:
      - ./src:/app
    networks:
      - tp3-network

  http:
    image: nginx:latest
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
    networks:
      - tp3-network

networks:
  tp3-network:
    driver: bridge
